import React from 'react';

interface ReportPageProps {
  pageNumber: number;
  title: string;
  children: React.ReactNode;
  companyName?: string;
}

export default function ReportPage({ pageNumber, title, children, companyName = 'Business Analytics' }: ReportPageProps) {
  return (
    <div className="report-page bg-white shadow-lg rounded-lg p-8 mb-6 min-h-[1000px] relative" style={{ pageBreakAfter: 'always' }}>
      <div className="border-b-2 border-primary pb-4 mb-6">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">{title}</h1>
            <p className="text-sm text-gray-500 mt-1">{companyName}</p>
          </div>
          <div className="text-right">
            <div className="text-sm text-gray-500">Page {pageNumber}</div>
            <div className="text-xs text-gray-400 mt-1">
              {new Date().toLocaleDateString('en-US', { 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric' 
              })}
            </div>
          </div>
        </div>
      </div>
      
      <div className="report-content">
        {children}
      </div>
      
      <div className="absolute bottom-8 left-8 right-8 border-t border-gray-200 pt-4">
        <p className="text-xs text-gray-400 text-center">
          Generated by Business Report Generator | Confidential
        </p>
      </div>
    </div>
  );
}
